### ISSUE TITLE
Stream music audio to single devices

### ISSUE THREAD

**Issue by mcollica** [woutervanwijk/Mopidy-MusicBox-Webclient#281] opened 2021-10-23 15:39 UTC
Is it possible to stream audio to single devices instead of playing it with the device Mopidy is installed in?

**Comment by kingosticks** [comment] 2021-10-23 17:05
If you are looking for a webclient that does this then the best bet is iris which has close integration with snapcast. Otherwise I already answered the duplicate of this question posted to Mopidy's github page.

**Closed as completed** 2021-10-23 17:05 UTC
